package db

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
)

// LinkOverlay records that one archived asset is the drawn-on layer of another.
//
// It is keyed on the overlay's content hash rather than its asset id, which is
// not a convenience: the id is generated by the database and a reindex from
// manifest.jsonl generates a different one, while the sha256 is the bytes and
// survives anything. The importer already holds it — an upload answers with it
// — and the manifest line written beside this call stores the same value, so a
// rebuilt archive can restore the link without re-reading the export.
//
// Both ends are written together, and this is the only place either is set:
//
//   - overlay_asset_id on the photo, which is how the composite is built.
//   - is_overlay on the overlay, which is how the timeline knows not to draw
//     a transparent PNG of somebody's handwriting as though it were a photo.
//
// Idempotent, because a re-run of an import is how anyone recovers a
// half-finished one. Linking an asset to itself is refused rather than stored:
// it would hide a photograph from the timeline permanently and there is no
// filename in any export that could legitimately produce it.
func (s *Store) LinkOverlay(ctx context.Context, assetID, overlaySHA256 string) error {
	if overlaySHA256 == "" {
		return errors.New("an overlay link needs the overlay's sha256")
	}

	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin transaction: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	var overlayID string
	err = tx.QueryRow(ctx, `select id::text from assets where sha256 = $1`, overlaySHA256).Scan(&overlayID)
	if errors.Is(err, pgx.ErrNoRows) {
		return fmt.Errorf("%w: no archived asset has sha256 %s", ErrNotFound, overlaySHA256)
	}
	if err != nil {
		return fmt.Errorf("look up overlay %s: %w", overlaySHA256, err)
	}
	if overlayID == assetID {
		return fmt.Errorf("asset %s cannot be its own overlay", assetID)
	}

	tag, err := tx.Exec(ctx,
		`update assets set overlay_asset_id = $2::uuid where id = $1::uuid`, assetID, overlayID)
	if err != nil {
		return fmt.Errorf("link overlay to %s: %w", assetID, err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}

	if _, err := tx.Exec(ctx,
		`update assets set is_overlay = true where id = $1::uuid`, overlayID); err != nil {
		return fmt.Errorf("mark %s as an overlay: %w", overlayID, err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit overlay link: %w", err)
	}
	return nil
}
